version: '3.8'

services:
  web:
    image: 'ticket-club-web:latest'
    container_name: ticket-club-web
    ports:
      - '3000:3000'
    env_file:
      - .env
  nginx:
    image: 'ticket-club-nginx:latest'
    container_name: ticket-club-nginx
    ports:
      - '80:80'
    depends_on:
      - web
networks:
  default:
    driver: bridge
