version: '3.8'

services:
  redis-node1:
    image: redis
    container_name: redis-node1
    restart: always
    network_mode: 'host'
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - ./redis-7000.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000

  redis-node2:
    image: redis
    container_name: redis-node1
    restart: always
    network_mode: 'host'
    ports:
      - 7001:7001
      - 17000:17000
    volumes:
      - ./redis-7001.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7001

  redis-node3:
    image: redis
    container_name: redis-node1
    restart: always
    network_mode: 'host'
    ports:
      - 7002:7002
      - 17000:17000
    volumes:
      - ./redis-7002.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 7002
