version: '3.8'

services:
  redis-node1:
    image: redis
    container_name: redis-node1
    restart: always
    network_mode: 'host'
    volumes:
      - ./redis-7000.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node2:
    image: redis
    container_name: redis-node2
    restart: always
    network_mode: 'host'
    volumes:
      - ./redis-7001.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node3:
    image: redis
    container_name: redis-node3
    restart: always
    network_mode: 'host'
    volumes:
      - ./redis-7002.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
